/*
 * ParseBarcodeReadTest
 */
package net.maizegenetics.analysis.gbs;

import net.maizegenetics.analysis.gbs.v2.GBSSimData;
import net.maizegenetics.util.Utils;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

/**
 * Tests legacy {@link ParseBarcodeRead} barcode key-file parsing using the simulated key file
 * generated by {@link GBSSimData}. The simulated key file is deliberately compatible with the
 * legacy positional parser (non-empty column&nbsp;H / LibraryPrepID).
 *
 * @author terry (original), rewritten for simulated data
 */
public class ParseBarcodeReadTest {

    public ParseBarcodeReadTest() {
    }

    @Test
    public void testParseBarcodeRead() throws Exception {
        GBSSimData sim = GBSSimData.createUnder("ParseBarcode");

        ParseBarcodeRead pbr = getParseBarcodeRead(sim.fastqFile.toString(), sim.keyFile.toString(), "ApeKI");

        // Every simulated taxon has a distinct barcode on the single simulated flowcell/lane.
        assertEquals(sim.taxa.size(), pbr.getBarCodeCount());
    }

    private ParseBarcodeRead getParseBarcodeRead(String fastqFile, String keyFilename, String enzyme) {

        String[] np = Utils.getFilename(fastqFile).split("_");

        String flowcell;
        String lane;
        if (np.length == 3) {
            flowcell = np[0];
            lane = np[1];
        } else if (np.length == 5) {
            flowcell = np[1];
            lane = np[3];
        } else if (np.length == 4) {
            flowcell = np[0];
            lane = np[2];
        } else if (np.length == 6) {
            flowcell = np[1];
            lane = np[3];
        } else {
            System.out.println("Error in parsing file name: " + fastqFile);
            return null;
        }

        ParseBarcodeRead result = new ParseBarcodeRead(keyFilename, enzyme, flowcell, lane);
        System.out.println("Fastq File: " + fastqFile + "  Key File: " + keyFilename + "  Enzyme: " + enzyme
                + "  Flowcell: " + flowcell + "  Lane: " + lane + "  Total Barcodes Found: " + result.getBarCodeCount());
        return result;
    }
}
