/**
 *
 */
package net.maizegenetics.analysis.gbs.v2;

import net.maizegenetics.dna.tag.TagData;
import net.maizegenetics.dna.tag.TagDataSQLite;
import net.maizegenetics.util.LoggingUtils;

import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

/**
 * Property-based rehabilitation of the GBSv2 pipeline-quality test.
 *
 * <p>The original test evaluated biological SNP-call quality against the real maize chr9/10 reference:
 * it required a large downloaded reference genome, a pre-made bowtie2 SAM, and HM3/conserved-site
 * golden position lists, and computed power/Type-I-error ratios and absolute SNP counts (~9631) that
 * are only meaningful against real maize data. It also shelled out to a hardcoded {@code bowtie2}
 * binary and wrote to hardcoded {@code /Users/lcj34} paths, so it could not run in CI.</p>
 *
 * <p>This rewrite drives the full GBSv2 pipeline (GBSSeqToTagDB then TagExport then a synthesized SAM
 * then Discovery) on a tiny deterministic data set generated by {@link GBSSimData}, and asserts on
 * invariants that hold regardless of platform: Discovery neither adds nor removes tags, and it calls
 * exactly one SNP per injected SNP locus. Both the with-reference and without-reference code paths are
 * exercised. The biological HM3/conserved-site quality evaluation is intentionally dropped (it is
 * inseparable from the real maize fixtures).</p>
 *
 * @author lcj34 (original), rehabilitated for self-generated data
 */
public class EvaluateSNPCallQualityOfPipelineTest {

    @Test
    public void pipelineWithReferenceTest() throws Exception {
        runPipeline(true);
    }

    @Test
    public void pipelineWithoutReferenceTest() throws Exception {
        runPipeline(false);
    }

    private void runPipeline(boolean withReference) throws Exception {
        LoggingUtils.setupDebugLogging();
        GBSSimData sim = GBSSimData.createUnder(withReference ? "EvaluateSNP_ref" : "EvaluateSNP_noref");
        sim.buildDatabaseThroughSam();

        int tagsBeforeDiscovery = sim.dbTagCount();
        assertTrue("Pipeline should store tags before discovery", tagsBeforeDiscovery > 0);

        sim.runDiscovery(withReference);

        assertEquals("Discovery must not add or remove tags",
                tagsBeforeDiscovery, sim.dbTagCount());

        TagData tagData = new TagDataSQLite(sim.dbFile.toString());
        int snpCount = tagData.getSNPPositions().size();
        ((TagDataSQLite) tagData).close();

        System.out.println("EvaluateSNPCallQualityOfPipelineTest (withReference=" + withReference
                + "): SNP positions called = " + snpCount);
        assertTrue("Discovery should call at least one SNP", snpCount > 0);
        assertEquals("Discovery should call exactly one SNP per injected SNP locus",
                sim.numSnpLoci, snpCount);
    }
}
